baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Show reading time in minutes for posts
  showReadingTime = false
  # Custom css
  custom_css = [
    "css/override-post.css", 
    "css/override-footer.css",
    "css/override-header.css"
  ]

[languages]
  [languages.en]
    title = "psyfer"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "More"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "oliver@psyfer:~$"
      logoHomeLink = "/home"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/Resume"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/Projects"
